#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /{_locale}
    controller: App\Controller\AppController::home
    requirements:
        _locale: "%app_locales%"
    defaults:
        template: app/index.html.twig
        _locale: "%locale%"
